# Generated by Django 5.1.6 on 2025-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_category', models.CharField(choices=[('HA', 'HomeAppliances'), ('KT', 'Kitchen'), ('GM', 'Gaming'), ('WK', 'Work')], max_length=50)),
                ('card_image', models.ImageField(upload_to='category_images')),
                ('card_title', models.CharField(max_length=50)),
            ],
        ),
    ]
