# Generated by Django 5.1.6 on 2025-03-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrationuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationUser',
        ),
    ]
