# Generated by Django 5.1.6 on 2025-03-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImages',
            field=models.ImageField(default=1, upload_to='product_images'),
        ),
    ]
