# Generated by Django 5.1.6 on 2025-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_card',
            name='link',
            field=models.CharField(choices=[('/personalHealth/', 'Personal Health'), ('/smartPhones/', 'Smart Phones'), ('/homeAppliances/', 'Home Appliances'), ('/gamingGadgets/', 'Gaming Gadgets')], default='/electronics/', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
