# Generated by Django 5.1.6 on 2025-03-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_card_link_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GG', 'Gaming Gadgets'), ('MAA', 'Mobiles & Accessories'), ('LAA', 'Laptops & Accessories'), ('TAHE', 'TV & Home Entertainment'), ('OAS', 'Office & Stationery')], max_length=50),
        ),
    ]
