# Generated by Django 5.1.6 on 2025-03-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_modelcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
