# Generated by Django 5.1.6 on 2025-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='addressType',
            field=models.CharField(choices=[('H', 'Home'), ('O', 'Office')], default='H', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
