# Generated by Django 5.1.6 on 2025-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_useraddress_fullname_useraddress_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='addressType',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='H', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='fullName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
