# Generated by Django 5.1.6 on 2025-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_useraddress_addresstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
