# Generated by Django 5.1.6 on 2025-03-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
