# Generated by Django 5.1.6 on 2025-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('15', '15 minuets'), ('12', '12 minuets'), ('9', '9 minuets'), ('6', '6 minuets'), ('3', '3 minuets'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
