# Generated by Django 5.1.6 on 2025-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_userorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousalImages', models.ImageField(default=1, upload_to='carousal_image')),
                ('imageName', models.CharField(default='carousal_images', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('15', '15 minuets'), ('12', '12 minuets'), ('9', '9 minuets'), ('6', '6 minuets'), ('3', '3 minuets'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='15', max_length=20),
        ),
    ]
