# Generated by Django 5.1.6 on 2025-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months_Spacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_product_heading', models.CharField(max_length=60)),
                ('first_product_description', models.CharField(max_length=300)),
                ('first_product_p1', models.CharField(max_length=250)),
                ('first_product_p2', models.CharField(max_length=170)),
                ('first_product_p3', models.CharField(max_length=50)),
                ('first_product_video', models.FileField(upload_to='Months_Spacial')),
                ('poster', models.ImageField(default=1, upload_to='Months_Spacial')),
                ('secund_product_heading', models.CharField(max_length=60)),
                ('secund_product_description', models.CharField(max_length=300)),
                ('secund_product_p1', models.CharField(max_length=250)),
                ('secund_product_p2', models.CharField(max_length=170)),
                ('secund_product_p3', models.CharField(max_length=50)),
                ('secund_product_video', models.FileField(upload_to='Months_Spacial')),
            ],
        ),
    ]
