# Generated by Django 5.1.6 on 2025-04-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_months_spacial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.CharField(choices=[('15', '15 minis'), ('30', '30 minis'), ('01', '01 hur')], default='15', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('one unit', '1 Unit'), ('set', 'Set'), ('combo', 'Combo')], default='one unit', max_length=20),
        ),
    ]
