# Generated by Django 5.1.6 on 2025-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_product_time_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('One unit', '1 Unit'), ('Set', 'Set'), ('Combo', 'Combo')], default='one unit', max_length=20),
        ),
    ]
