# Generated by Django 5.1.6 on 2025-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_product_time_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(choices=[('15 MINIS', '15 minis'), ('30 MINIS', '30 minis'), ('01 HUR', '01 hur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('One Unit', '1 Unit'), ('Set', 'Set'), ('Combo', 'Combo')], max_length=20),
        ),
    ]
