# Generated by Django 5.1.6 on 2025-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_product_time_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='point2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='point3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='point4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
