# Generated by Django 5.1.6 on 2025-04-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImages1',
            field=models.ImageField(default=1, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='productImages2',
            field=models.ImageField(default=1, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='productImages3',
            field=models.ImageField(default=1, upload_to='product_images'),
        ),
    ]
