# Generated by Django 5.1.6 on 2025-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_product_productimages1_product_productimages2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RAM', 'PC RAM'), ('GPC', 'GRAPHICS CARDS'), ('AIC', 'AIR COOLER'), ('HHD', 'HARD DRIVE'), ('PWS', 'POWER SUPPLY'), ('SSD', 'SSD'), ('LIQ', 'LIQUID COOLER'), ('PRS', 'PROCESSOR'), ('MTB', 'MOTHERBOARD')], max_length=50),
        ),
    ]
