# Generated by Django 5.1.6 on 2025-04-19 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooler_builds', to='core.product')),
                ('graphics_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphics_builds', to='core.product')),
                ('hdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd_builds', to='core.product')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard_builds', to='core.product')),
                ('power_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_builds', to='core.product')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_builds', to='core.product')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram_builds', to='core.product')),
                ('ssd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssd_builds', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
