# Generated by Django 5.1.6 on 2025-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_custompcbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcbuild',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
