# Generated by Django 5.1.6 on 2025-04-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_custompcbuild_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcbuild',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraddress'),
        ),
        migrations.AddField(
            model_name='custompcbuild',
            name='status',
            field=models.CharField(choices=[('15', '15 minuets'), ('12', '12 minuets'), ('9', '9 minuets'), ('6', '6 minuets'), ('3', '3 minuets'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='15', max_length=20),
        ),
    ]
