# Generated by Django 5.1.6 on 2025-04-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_custompcbuild_address_custompcbuild_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompcbuild',
            name='address',
        ),
        migrations.RemoveField(
            model_name='custompcbuild',
            name='status',
        ),
    ]
