# Generated by Django 5.1.6 on 2025-04-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_custompcbuild_address_custompcbuild_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompcbuild',
            name='address',
        ),
        migrations.RemoveField(
            model_name='custompcbuild',
            name='status',
        ),
        migrations.CreateModel(
            name='CustomBuiltOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraddress')),
                ('cooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cooler', to='core.product')),
                ('graphics_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_graphics', to='core.product')),
                ('hdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_hdd', to='core.product')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_motherboard', to='core.product')),
                ('power_supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_power', to='core.product')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_processor', to='core.product')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ram', to='core.product')),
                ('ssd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ssd', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
