# Generated by Django 5.1.6 on 2025-04-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_custompcbuild_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuiltorder',
            name='status',
            field=models.CharField(choices=[('15', '15 minuets'), ('12', '12 minuets'), ('9', '9 minuets'), ('6', '6 minuets'), ('3', '3 minuets'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='15', max_length=20),
        ),
    ]
