# Generated by Django 5.1.6 on 2025-04-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_custombuiltorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcbuild',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_builds', to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RAM', 'PC RAM'), ('GPC', 'GRAPHICS CARDS'), ('AIC', 'AIR COOLER'), ('HHD', 'HARD DRIVE'), ('PWS', 'POWER SUPPLY'), ('SSD', 'SSD'), ('LIQ', 'LIQUID COOLER'), ('PRS', 'PROCESSOR'), ('MTB', 'MOTHERBOARD'), ('CBT', 'CABINET'), ('MTR', 'MONITOR')], max_length=50),
        ),
    ]
