# Generated by Django 5.1.6 on 2025-04-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_custompcbuild_cabinet_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuiltorder',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cabinet', to='core.product'),
        ),
    ]
