# Generated by Django 5.1.6 on 2025-04-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_custombuiltorder_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RAM', 'PC RAM'), ('GPC', 'GRAPHICS CARDS'), ('AIC', 'AIR COOLER'), ('HHD', 'HARD DRIVE'), ('PWS', 'POWER SUPPLY'), ('SSD', 'SSD'), ('LIQ', 'LIQUID COOLER'), ('PRS', 'PROCESSOR'), ('MTB', 'MOTHERBOARD'), ('CBT', 'CABINET'), ('MTR', 'MONITOR'), ('WEK', 'WEEKLY DEAL'), ('SPA', 'SPACIAL DEAL')], max_length=50),
        ),
    ]
