# Generated by Django 5.1.6 on 2025-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_product_deal_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ram', 'PC RAM'), ('Graphics Card', 'GRAPHICS CARDS'), ('Air Cooler', 'AIR COOLER'), ('Hard Disk', 'HARD DRIVE'), ('Power Supply', 'POWER SUPPLY'), ('Solid State Drive', 'SSD'), ('Liquid Cooler', 'LIQUID COOLER'), ('Processor', 'PROCESSOR'), ('Motherboard', 'MOTHERBOARD'), ('Cabinet', 'CABINET'), ('Monitor', 'MONITOR')], max_length=50),
        ),
    ]
