# Generated by Django 5.1.6 on 2025-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_video',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_video',
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='first_product_img',
            field=models.ImageField(default=True, null=True, upload_to='Months_Spacial)'),
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='secund_product_img',
            field=models.ImageField(default=True, null=True, upload_to='Months_Spacial)'),
        ),
    ]
