# Generated by Django 5.1.6 on 2025-05-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
