# Generated by Django 5.1.6 on 2025-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_custombuiltorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_p1',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_p2',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_p3',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_img',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_p1',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_p2',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_p3',
        ),
    ]
