# Generated by Django 5.1.6 on 2025-05-03 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_months_spacial_first_product_p1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_description',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_heading',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='first_product_img',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_description',
        ),
        migrations.RemoveField(
            model_name='months_spacial',
            name='secund_product_heading',
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='news_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images'),
        ),
        migrations.AddField(
            model_name='months_spacial',
            name='news_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
