# Generated by Django 5.1.6 on 2025-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_months_spacial_first_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='months_spacial',
            name='news_tital',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
