# Generated by Django 5.1.6 on 2025-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_months_spacial_news_tital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months_spacial',
            name='news_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
