# Generated by Django 5.1.6 on 2025-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombuiltorder',
            name='status',
            field=models.CharField(choices=[('15', '3 Hur'), ('12', 'Find Product'), ('9', 'Assembling'), ('6', 'Software'), ('3', 'Pack and Outofdelivrary'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='03', max_length=20),
        ),
    ]
