# Generated by Django 5.1.6 on 2025-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_custombuiltorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuiltorder',
            name='user_order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
